catalog
catalogDescription
	"Returns a paragraph describing the project"
	^ 'This library provides: 
- Parses JSON/XML return values into Smalltalk objects.
- Provides several query wrapper methods and accompanying result transformations to enable direct access to single-valued query results, vectors of query results, and boolean results (for ASK queries).
- Allow either HTTP GET or HTTP POST to be used when sending queries.
	
You can add other SPARQL endpoints by subclassing main root class. Other interesting endpoints (like Musicbrainz, U.S. Census, Semantic Crunchbase, etc) are listed in the W3.org web site https://www.w3.org/wiki/SparqlEndpoints

'